[project]
name = "vp2py"
version = "4.0.0"
description = "An implementation of a Varphi-to-Python compiler."
readme = "README.md"
authors = [
    { name = "Varphi", email = "support@varphi-lang.com" }
]
requires-python = ">=3.10"
dependencies = [
    "typer",
    "varphi-devkit>=4.0.0",
]

[project.scripts]
vp2py = "vp2py.cli:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black",
    "pillow>=12.3.0",
    "pyinstaller>=6.22.2",
    "pytest",
    "requests>=2.34.2",
    "vermin",
]
